### ISSUE TITLE
[Upstream Provider Request] [New Feature]: Complete implementation of ability to form partnerships between users via built in webUI

### ISSUE THREAD

**Issue by emperorstarfinder** [Virtual-Universe/Virtual-Universe-Stable-Dev#2]
### Steps to reproduce

This is a feature request.
### Expected behaviour

Upstream Provider WhiteCore-Sim requests we look at complete implementation of the ability to establish partnerships via the webUI.  The initial skeleton for this is already in the repository.
### Actual behaviour

The actual behavior when completed is that the user will be able to establish partnerships with other users via the webUI.  Similar to how Secondlife does it now.
### Server configuration

**Operating system**:

Not Applicable

**Web server:**

Not Applicable

**Database:**

Not Applicable

**Virtual Universe version:**

Request for Version 1.0.3 Release
### Logs

Please make sure that Virtual Universe has made an log-file and include a link to it here

**Comment by RyujinnJakka** [comment]
Will this feature include the ability to partner with more then one person or entity ad discussed about 2 years ago or just the bare sl basics?

**Comment by NoahStarfinder** [comment]
Good morning,

This request was submitted to the development team by an upstream provider.  The request provided internally only refers to the standard Secondlife Like Partnership functionality.  

Currently viewers do not support the ability to allow a user to partner with more then one partner at the same time (wouldn't be realistic anyway) nor does it generally allow the ability to add one's business in the user's profile.  

Your question refers to a separate feature idea/ request which is pending on the Second Galaxy Development Team's Internal Tracker.  There is a chance it could be implemented prior to the Virtual Universe Version 1.0.3 Release in June 2017, but it is more likely to be implemented in Virtual Universe Version 1.0.4 Release in June 2018.

Feel free to open issues for bugs you find or feature requests and answer the necessary questions.  If your a member of the team who is returning please be sure to contact @emperorstarfinder to receive assignment to a work group on the development team.  You can always find us in IRC of Freenode at: http://webchat.freenode.net?channels=%23galaxyfutures

Hope this helps

Noah Starfinder
Core Developer
Governing Body Vice Chair - North America
In-Galaxy Services and Features Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: noah@secondgalaxy.com
