### ISSUE TITLE
User Level

### ISSUE THREAD

**Issue by LifeGold** [Virtual-Universe/Virtual-Universe-Stable-Dev#34]
Hi all. Wanted to ask where to find the user Levels and the list of what they offer to edit it.

**Comment by NoahStarfinder** [comment]
Good morning,

I am not sure what you are wanting to edit as far as user levels here, however it is not wise to be editing the user levels as the viewers expect the levels the way they are right now.  Additionally by editing the user levels you could in fact be breaking other services that need the user levels the way they currently are without actually intending to break those services.  

I think some more information is needed here before we can say for sure what would be needed as far as editing.  

Noah Starfinder
Core Developer
Governing Body Vice Chair - North America
In-Galaxy Services and Features Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: noah@secondgalaxy.com

**Comment by LifeGold** [comment]
For example level 100 gives users the ability to take a copy of the object. Here I need to remove this feature from level 100. Well, something like that.

**Comment by NoahStarfinder** [comment]
Hmmm.  

First thing to remember here is that the god levels i.e. Level 100 through 250 are in fact meant to be able to override certain permissions for the purposes of grid maintenance and support.  You should not ever elevate users to this level unless you trust them and they are on your grid's staff.  

That being said the concern about people being able to use accounts which have been elevated to god levels to circumvent permissions systems is a valid concern.  I will add this to my list to look at further as it does raise a valid concern.  

Noah Starfinder
Core Developer
Governing Body Vice Chair - North America
In-Galaxy Services and Features Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: noah@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
@NoahStarfinder it does look like there is an issue here.  In testing I did find that you could take copies of objects that that permission hasn't been set.  Members of our team's staff have also indicated they noticed the same thing with their staff accounts.  Unsure if this is happening with normal users just yet.  

If it is I would be inclined to change this to a bug report as it would appear there is an issue with the permissions system again.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com

**Comment by NoahStarfinder** [comment]
In further testing, It appears the culprit is the permissions check that tells if the user is in God Mode.  This would in fact be a bug.  Great catch.  I will fix this as quick as I can.

Noah Starfinder
Core Developer
Governing Body Vice Chair - North America
In-Galaxy Services and Features Developer
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: noah@secondgalaxy.com

**Comment by emperorstarfinder** [comment]
This has also been added to our internal issue tracker so we can fix this as quick as possible.  Hopefully it should be fixed before the June Release.

Emperor Starfinder
Founder
Chief Executive Officer
Core Developer
Governing Body Chair
Grid Architecture Developer
Work Group Leader
Grid Architecture Development Work Group
Second Galaxy Development Team
Email: emperor@secondgalaxy.com
